/*
 * This file is generated by jOOQ.
 */
package games.classifier.manager.infrastructure.adapters.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Games implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Short gameCode;
    private final String name;

    public Games(Games value) {
        this.id = value.id;
        this.gameCode = value.gameCode;
        this.name = value.name;
    }

    public Games(
        Long id,
        Short gameCode,
        String name
    ) {
        this.id = id;
        this.gameCode = gameCode;
        this.name = name;
    }

    /**
     * Getter for <code>public.games.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.games.game_code</code>.
     */
    public Short getGameCode() {
        return this.gameCode;
    }

    /**
     * Getter for <code>public.games.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Games other = (Games) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gameCode == null) {
            if (other.gameCode != null)
                return false;
        }
        else if (!this.gameCode.equals(other.gameCode))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gameCode == null) ? 0 : this.gameCode.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Games (");

        sb.append(id);
        sb.append(", ").append(gameCode);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
