/*
 * This file is generated by jOOQ.
 */
package games.classifier.manager.infrastructure.adapters.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Game implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final Short gameId;
    private final String name;
    private final String legalName;
    private final Long priceDefault;
    private final Integer countMls;

    public Game(Game value) {
        this.id = value.id;
        this.gameId = value.gameId;
        this.name = value.name;
        this.legalName = value.legalName;
        this.priceDefault = value.priceDefault;
        this.countMls = value.countMls;
    }

    public Game(
        Long id,
        Short gameId,
        String name,
        String legalName,
        Long priceDefault,
        Integer countMls
    ) {
        this.id = id;
        this.gameId = gameId;
        this.name = name;
        this.legalName = legalName;
        this.priceDefault = priceDefault;
        this.countMls = countMls;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.game.game_id</code>.
     */
    public Short getGameId() {
        return this.gameId;
    }

    /**
     * Getter for <code>public.game.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.game.legal_name</code>.
     */
    public String getLegalName() {
        return this.legalName;
    }

    /**
     * Getter for <code>public.game.price_default</code>.
     */
    public Long getPriceDefault() {
        return this.priceDefault;
    }

    /**
     * Getter for <code>public.game.count_mls</code>.
     */
    public Integer getCountMls() {
        return this.countMls;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Game other = (Game) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gameId == null) {
            if (other.gameId != null)
                return false;
        }
        else if (!this.gameId.equals(other.gameId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.legalName == null) {
            if (other.legalName != null)
                return false;
        }
        else if (!this.legalName.equals(other.legalName))
            return false;
        if (this.priceDefault == null) {
            if (other.priceDefault != null)
                return false;
        }
        else if (!this.priceDefault.equals(other.priceDefault))
            return false;
        if (this.countMls == null) {
            if (other.countMls != null)
                return false;
        }
        else if (!this.countMls.equals(other.countMls))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gameId == null) ? 0 : this.gameId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.legalName == null) ? 0 : this.legalName.hashCode());
        result = prime * result + ((this.priceDefault == null) ? 0 : this.priceDefault.hashCode());
        result = prime * result + ((this.countMls == null) ? 0 : this.countMls.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Game (");

        sb.append(id);
        sb.append(", ").append(gameId);
        sb.append(", ").append(name);
        sb.append(", ").append(legalName);
        sb.append(", ").append(priceDefault);
        sb.append(", ").append(countMls);

        sb.append(")");
        return sb.toString();
    }
}
