/*
 * This file is generated by jOOQ.
 */
package games.classifier.manager.infrastructure.adapters.db.tables;


import games.classifier.manager.infrastructure.adapters.db.Keys;
import games.classifier.manager.infrastructure.adapters.db.Public;
import games.classifier.manager.infrastructure.adapters.db.tables.records.TicketsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tickets extends TableImpl<TicketsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tickets</code>
     */
    public static final Tickets TICKETS = new Tickets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketsRecord> getRecordType() {
        return TicketsRecord.class;
    }

    /**
     * The column <code>public.tickets.id</code>.
     */
    public final TableField<TicketsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.tickets.game_id</code>.
     */
    public final TableField<TicketsRecord, Long> GAME_ID = createField(DSL.name("game_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tickets.barcode</code>.
     */
    public final TableField<TicketsRecord, String> BARCODE = createField(DSL.name("barcode"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.tickets.status</code>.
     */
    public final TableField<TicketsRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false), this, "");

    private Tickets(Name alias, Table<TicketsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Tickets(Name alias, Table<TicketsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.tickets</code> table reference
     */
    public Tickets(String alias) {
        this(DSL.name(alias), TICKETS);
    }

    /**
     * Create an aliased <code>public.tickets</code> table reference
     */
    public Tickets(Name alias) {
        this(alias, TICKETS);
    }

    /**
     * Create a <code>public.tickets</code> table reference
     */
    public Tickets() {
        this(DSL.name("tickets"), null);
    }

    public <O extends Record> Tickets(Table<O> child, ForeignKey<O, TicketsRecord> key) {
        super(child, key, TICKETS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketsRecord, Long> getIdentity() {
        return (Identity<TicketsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketsRecord> getPrimaryKey() {
        return Keys.TICKETS_PKEY;
    }

    @Override
    public List<ForeignKey<TicketsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKETS__FK_GAME_ID);
    }

    private transient Games _games;

    /**
     * Get the implicit join path to the <code>public.games</code> table.
     */
    public Games games() {
        if (_games == null)
            _games = new Games(this, Keys.TICKETS__FK_GAME_ID);

        return _games;
    }

    @Override
    public Tickets as(String alias) {
        return new Tickets(DSL.name(alias), this);
    }

    @Override
    public Tickets as(Name alias) {
        return new Tickets(alias, this);
    }

    @Override
    public Tickets as(Table<?> alias) {
        return new Tickets(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(String name) {
        return new Tickets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(Name name) {
        return new Tickets(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(Table<?> name) {
        return new Tickets(name.getQualifiedName(), null);
    }
}
