/*
 * This file is generated by jOOQ.
 */
package games.classifier.manager.infrastructure.adapters.db;


import games.classifier.manager.infrastructure.adapters.db.tables.Databasechangelog;
import games.classifier.manager.infrastructure.adapters.db.tables.Databasechangeloglock;
import games.classifier.manager.infrastructure.adapters.db.tables.Game;
import games.classifier.manager.infrastructure.adapters.db.tables.Games;
import games.classifier.manager.infrastructure.adapters.db.tables.TGame;
import games.classifier.manager.infrastructure.adapters.db.tables.Tickets;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>public.games</code>.
     */
    public final Games GAMES = Games.GAMES;

    /**
     * The table <code>public.t_game</code>.
     */
    public final TGame T_GAME = TGame.T_GAME;

    /**
     * The table <code>public.tickets</code>.
     */
    public final Tickets TICKETS = Tickets.TICKETS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Game.GAME,
            Games.GAMES,
            TGame.T_GAME,
            Tickets.TICKETS
        );
    }
}
